{% set name = "meteostat" %}
{% set version = "1.6.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
  run:
    - python
    - numpy
    - pytz
    - pandas

test:
  source_files:
    - tests/
  imports:
    - meteostat
  commands:
    - pytest 
  requires:
    - pytest

